#!/bin/bash
root=$(pwd);
app_builds_dir="$root/app/build/outputs/apk/";
#log "UNISTALL :: previous app build";
adb uninstall com.zopnow;
apk_file=$app_builds_dir"app-debug.apk";
#log "INSTALL :: installing [$apk_file]";
adb install -r $apk_file;
#log "UNISTALL :: previous test build";
adb uninstall com.zopnow.test;
apk_file_test=$app_builds_dir"app-debug-androidTest-unaligned.apk";
echo $apk_file_test;
#log "INSTALL :: installing [$apk_file]";
adb install -r $apk_file_test;
